/** Define ids for each page. */
export const PAGE_IDS = {
  DIRECTORY: 'directory',
  MY_FOLDERS: 'my-folders',
  ADD_MEASURE: 'add-measure',
  VIEW_BILL: 'view-bill',
  ADD_TESTIMONY: 'add-testimony',
  VIEW_TESTIMONY: 'view-testimony',
  EDIT_TESTIMONY: 'edit-testimony',
  INBOX: 'inbox',
  CREATE_EMAIL: 'create-email',
  MANAGE_DATABASE: 'manage-database',
  MEMBERS: 'members',
  NOT_AUTHORIZED: 'not-authorized',
  MONITORING_REPORT: 'monitoring-report',
  NOT_FOUND: 'not-found',
  PROFILE: 'profile',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  CHANGE_PASSWORD: 'change-password',
};
